---
default_language_version:
  node: 12.19.0
  python: python3.7
default_stages:
  - commit
repos:
  - repo: https://github.com/andreoliwa/nitpick
    rev: v0.26.0
    hooks:
      - id: nitpick
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-blind-except == 0.2.0
          - flake8-builtins == 1.5.3
          - flake8-comprehensions == 3.5.0
          - flake8-django == 1.1.2
          - flake8-docstrings == 1.6.0
          - flake8-logging-format == 0.6.0
          - flake8-polyfill == 1.0.2
          - flake8-rst == 0.8.0
          - flake8-rst-docstrings == 0.2.3
          - mccabe == 0.6.1
          - pep8-naming == 0.11.1
          - pycodestyle == 2.7.0
          - pydocstyle == 6.1.1
          - pyflakes == 2.3.1
          - restructuredtext-lint == 1.3.2
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.730
    hooks:
      - id: mypy
