---
trigger:
  - master

variables:
  NPM_CONFIG_REGISTRY: https://pkgs.dev.azure.com/agos-labs/_packaging/agos-labs/npm/registry/
  NPM_CONFIG_USERCONFIG: $(Pipeline.Workspace)/.npmrc
  PIP_INDEX_URL: https://pkgs.dev.azure.com/agos-labs/_packaging/agos-labs/pypi/simple/
  PRE_COMMIT_HOME: $(Pipeline.Workspace)/pre-commit-cache

stages:
  - stage: QualityAssurance
    displayName: Quality Assurance
    pool:
      vmImage: "ubuntu-latest"
    jobs:
      - template: azure-pipelines/jobs/validate-toolchain-conformity.yaml
      - template: azure-pipelines/jobs/validate-commit-messages.yaml

  - stage: Release
    pool:
      vmImage: ubuntu-16.04
    condition:
      and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - template: azure-pipelines/jobs/semantic-version.yaml
      - job: PushToGitHub
        displayName: Push to GitHub
        dependsOn: SemanticVersion
        variables:
          GITHUB_URL: github.com/agos-tech/toolchain-config
          GITHUB_USERNAME: agos-release-manager
        steps:
          - checkout: self
            persistCredentials: true
          - script: git fetch origin $(Build.sourceBranch)
            displayName: Force fetch the source branch

          - script:
              git push
              "https://$(GITHUB_USERNAME):$(GITHUB_TOKEN)@$(GITHUB_URL)"
              FETCH_HEAD:$(Build.sourceBranch) --tags
            displayName: Push the source branch and tags
