---
trigger:
  - master

variables:
  - template: azure-pipelines/variables/base.yaml

stages:
  - template: azure-pipelines/stages/quality-assurance.yaml

  - stage: Release
    pool:
      vmImage: ubuntu-20.04
    condition:
      and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    variables:
      NPM_CONFIG_REGISTRY: https://pkgs.dev.azure.com/agos-labs/_packaging/agos-labs/npm/registry/
      NPM_CONFIG_USERCONFIG: $(Pipeline.Workspace)/.npmrc
    jobs:
      - template: azure-pipelines/jobs/semantic-version.yaml
      - job: PushToGitHub
        displayName: Push to GitHub
        dependsOn: SemanticVersion
        variables:
          GITHUB_URL: github.com/agos-tech/toolchain-config
          GITHUB_USERNAME: agos-release-manager
        steps:
          - checkout: self
            persistCredentials: true
          - script: git fetch origin $(Build.sourceBranch)
            displayName: Force fetch the source branch

          - script:
              git push
              "https://$(GITHUB_USERNAME):$(GITHUB_TOKEN)@$(GITHUB_URL)"
              FETCH_HEAD:$(Build.sourceBranch) --tags
            displayName: Push the source branch and tags
