---
stages:
  - stage: QualityAssurance
    displayName: Quality Assurance
    pool:
      vmImage: ubuntu-16.04
    jobs:
      - template: ../jobs/validate-toolchain-conformity.yaml
      - template: ../jobs/validate-commit-messages.yaml
