[nitpick.JSONFile]
file_names = ["package.json"]

["package.json".contains_json]
devDependencies = """
  {
    "@commitlint/cli": "^8.3.4",
    "@commitlint/config-conventional": "^8.3.4"
  }
"""
commitlint = """
  {
    "extends": [
      "@commitlint/config-conventional"
    ]
  }
"""


[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.2  # @commitlint/cli == 8.3.4
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional@8.3.4"]
"""
