[nitpick.files.present]
".pre-commit-config.yaml" = "Create the file with the contents below, then run 'pre-commit install'"


["pre-commit-config.yaml"]
default_stages = ["commit"]
default_language_version = {node = "12.19.0"}

[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/andreoliwa/nitpick
    rev: v0.29.0
    hooks:
      - id: nitpick
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
"""
