[[".prettierrc.yaml".contains]]
line = "proseWrap: always"
[[".prettierrc.yaml".contains]]
line = "trailingComma: all"


[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
"""
