---
default_language_version:
  node: 12.19.0
default_stages:
  - commit
repos:
  - repo: https://github.com/andreoliwa/nitpick
    rev: v0.26.0
    hooks:
      - id: nitpick
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        language_version: python3.7
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        exclude: ^(contrib/[^/]+/)?(docs|tests)/
        additional_dependencies:
          - flake8-blind-except == 0.1.1
          - flake8-builtins == 1.4.1
          - flake8-comprehensions == 3.0.1
          - flake8-docstrings == 1.5.0
          - flake8-logging-format == 0.6.0
          - flake8-rst == 0.7.1
          - flake8-rst-docstrings == 0.0.11
          - pep8-naming == 0.9.1
          - pydocstyle == 4.0.1
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.730
    hooks:
      - id: mypy
