---
default_language_version:
  node: 12.19.0
default_stages:
  - commit
repos:
  - repo: https://github.com/andreoliwa/nitpick
    rev: v0.22.2
    hooks:
      - id: nitpick
  - repo: https://github.com/prettier/prettier
    rev: 1.19.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
      - id: seed-isort-config
        args: [--exclude=^contrib/]
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        exclude: ^contrib/
        language_version: python3.7
        additional_dependencies:
          - toml == 0.10.0
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        exclude: ^(contrib/[^/]+/)?(docs|tests)/
        additional_dependencies:
          - flake8-blind-except == 0.1.1
          - flake8-builtins == 1.4.1
          - flake8-comprehensions == 3.0.1
          - flake8-docstrings == 1.5.0
          - flake8-logging-format == 0.6.0
          - flake8-rst == 0.7.1
          - flake8-rst-docstrings == 0.0.11
          - pep8-naming == 0.9.1
          - pydocstyle == 4.0.1
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.730
    hooks:
      - id: mypy
