["tox.ini".flake8]
# http://www.pydocstyle.org/en/3.0.0/error_codes.html
# Ignore C408: Sometimes readability trumps efficiency, and so we don't mandate dict
#   literals.
# Ignore D105: If a magic method needs a docstring its behaviour is probably unpythonic.
# Ignore D107: An __init__ that needs no docstring is a good thing.
# Ignore D202: pydocstyle triggers a false positive with inner functions defined after a
#   docstring, let Black handle this edge case.
# Ignore E203: black inserts a space before : in a slice, flake8 complains about it.
# Ignore E731: It is sometimes "better" to have named inline lambdas than full
#    functions.
# Ignore G100: We do not maintain a logging argument whitelist.
# Ignore RST304: The reST roles should not be validated by flake8.
# Ignore W503: Line breaks should be before binary operators, not after.
ignore = "C408,D105,D107,D202,E203,E731,G100,RST304,W503"
# Enable G: Check logging format.
enable-extensions = "B,G"
max-line-length = 88


[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-blind-except == 0.2.0
          - flake8-bugbear==21.4.3
          - flake8-builtins == 1.5.3
          - flake8-comprehensions == 3.5.0
          - flake8-docstrings == 1.6.0
          - flake8-logging-format == 0.6.0
          - flake8-polyfill == 1.0.2
          - flake8-rst == 0.8.0
          - flake8-rst-docstrings == 0.2.3
          - mccabe == 0.6.1
          - pep8-naming == 0.11.1
          - pycodestyle == 2.7.0
          - pydocstyle == 6.1.1
          - pyflakes == 2.3.1
          - restructuredtext-lint == 1.3.2
"""
