["pyproject.toml".tool.isort]
profile = "black"
lines_after_imports = 2
multi_line_output = 3


[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
"""
