["pyproject.toml".tool.poetry.dev-dependencies]
pre-commit = "~2.12.0"


[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: debug-statements
"""
