["pyproject.toml".tool.poetry.dev-dependencies]
pre-commit = "^1.20.0"


[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: debug-statements
"""
