["pyproject.toml".tool.poetry.dev-dependencies]
pre-commit = {version="^1.20.0", optional=true}


[["pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: debug-statements
"""
