---
jobs:
  - job: ValidateToolchainConformity
    displayName: Validate toolchain conformity
    container: $[ variables['flinters-container'] ]
    steps:
      - template: ../steps/yarn-dependencies.yaml

      - script: pre-commit run --all-files
        displayName: Run pre-commit hooks
