---
jobs:
  - job: ValidateCommitMessages
    displayName: Validate commit messages
    steps:
      - template: ../steps/yarn-dependencies.yaml

      - script: npx --no-install commitlint --from=origin/master
        displayName: Lint commit messages since master
