---
default_language_version:
  node: 12.19.0
default_stages:
  - commit
repos:
  - repo: https://github.com/andreoliwa/nitpick
    rev: v0.29.0
    hooks:
      - id: nitpick
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
