---
steps:
  - script: |
      echo "registry=$(NPM_CONFIG_REGISTRY)" > $(NPM_CONFIG_USERCONFIG)
      echo "always-auth=true" >> $(NPM_CONFIG_USERCONFIG)
    displayName: Configure npm for Azure Artifacts
  - task: npmAuthenticate@0
    inputs:
      workingFile: $(NPM_CONFIG_USERCONFIG)
    displayName: Authenticate npm for Azure Artifacts
