---
steps:
  - template: ./python-setup.yaml

  - script: poetry env use $(PYTHON_VERSION)
    displayName: Set Python version for Poetry
  - script:
      echo "##vso[task.setvariable variable=POETRY_ENV_DIR]$(poetry env info
      --path)"
    displayName: Define path to Poetry's virtual environment

  - task: Cache@2
    inputs:
      key: poetry | "$(Agent.OS)" | poetry.lock | "$(PYTHON_FULL_VERSION)"
      path: $(POETRY_ENV_DIR)
    displayName: Poetry environment cache
