---
steps:
  - template: ./python-setup.yaml

  - task: Cache@2
    inputs:
      key:
        pre-commit | "$(Agent.OS)" | .pre-commit-config.yaml |
        "$(PYTHON_FULL_VERSION)"
      path: $(PRE_COMMIT_HOME)
    displayName: Cache pre-commit hooks
  - script: pre-commit install
    displayName: Install pre-commit hooks
