---
steps:
  - template: ./poetry-dependencies.yaml

  - task: Cache@2
    inputs:
      key:
        pre-commit | "$(Agent.OS)" | .pre-commit-config.yaml |
        "$(PYTHON_FULL_VERSION)"
      restoreKeys: |
        pre-commit | "$(Agent.OS)" | .pre-commit-config.yaml
        pre-commit | "$(Agent.OS)"
        pre-commit
      path: $(PRE_COMMIT_HOME)
    displayName: Cache pre-commit hooks
  - script: poetry run pre-commit install
    displayName: Install pre-commit hooks
