---
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
      addToPath: true
  - script: |
      echo "##vso[task.setvariable variable=PYTHON_FULL_VERSION]$(python --version --version)"
      echo "##vso[task.setvariable variable=PYTHON_VERSION]$(python -c 'import platform; print(platform.python_version())')"
    displayName: Define Python version

  - template: authenticate-azure-npm.yaml
  - template: authenticate-azure-pip.yaml

  - script: pip install -r build-requirements.txt
    displayName: Install build requirements
