---
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
  - script:
      echo "##vso[task.setvariable variable=NODE_VERSION]$(node --version)"
    displayName: Define Node.js version

  - template: authenticate-azure-npm.yaml

  - task: Cache@2
    inputs:
      key: yarn | "$(Agent.OS)" | yarn.lock | "$(NODE_VERSION)"
      restoreKeys: |
        yarn | "$(Agent.OS)" | yarn.lock
        yarn | "$(Agent.OS)"
      path: node_modules
    displayName: Cache JavaScript dependencies
  - script: yarn install --frozen-lockfile --production=false
    displayName: Install JavaScript requirements
